### ISSUE TITLE
Allocating unneeded large buffers

### ISSUE THREAD

**Issue by kalyankondapally** [intel/IA-Hardware-Composer#243]
Tracing in overlaylayer shows we are allocating buffers of large size which fail fb creation:

SetBuffer: buffer 2880 2560   -> Buffer size
02-18 20:21:11.651  1969  2149 E iahwcomposer: SetBuffer: layer 1920 1080  -> Frame rect

This might be an alignment issue in buffer manager side.

**Comment by kalyankondapally** [comment]
seems to be done when incoming layers have size of 1920, 1080. We should track down in Minigbm side

**Comment by harishkrupo** [comment]
What about the behavior with GBM?

**Comment by kalyankondapally** [comment]
not sure

**Comment by harishkrupo** [comment]
Ok, will check with GBM.

**Comment by kalyankondapally** [comment]
Also, probably when nativehandler is initialized, we should set the maximum width and height and limit it to them when allocating memory.

**Comment by harishkrupo** [comment]
yeah, that can be done. But even then if the maximum W/H is 1920x1080 we will still end up allocating the same?

**Comment by kalyankondapally** [comment]
if requested size is larger than this, we should limit it to this size

**Comment by harishkrupo** [comment]
Ran the linux_test app with GBM. it is allocating properly. Need to check if this is a minigbm issue or Android side allocation.

**Comment by kalyankondapally** [comment]
seems like Android FW is requesting these.
