### ISSUE TITLE
Fix warnings.

### ISSUE THREAD

**Issue by kalyankondapally** [intel/IA-Hardware-Composer#258]
We shouldn't have any warnings on Android builds.

**Comment by kalyankondapally** [comment]
@ravelar is going to look at this.

**Comment by stripes416** [comment]
@kalyankondapally I think you mean @csravelar. I'm not sure who 'ravelar' is?

**Comment by kalyankondapally** [comment]
@stripes416 He has two id's :)

**Comment by csravelar** [comment]
My intel given github.intel.com id is ravelar. My github is csravelar. Looks like we tagged some random guy hehe.

**Comment by kalyankondapally** [comment]
1 warning generated.
[ 31% 14/44] target  C++: libhwcomposer_common <= vendor/intel/external/android_ia/hwcomposer/common/core/gpudevice.cpp
vendor/intel/external/android_ia/hwcomposer/common/core/gpudevice.cpp:581:17: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Wsign-compare]
      if (index < num_displays) {
          ~~~~~ ^ ~~~~~~~~~~~~
1 warning generated.
[ 38% 17/44] target  C++: libhwcomposer_common <= vendor/intel/external/android_ia/hwcomposer/common/core/nesteddisplay.cpp
vendor/intel/external/android_ia/hwcomposer/common/core/nesteddisplay.cpp:190:54: warning: unused parameter 'source_layers' [-Wunused-parameter]
bool NestedDisplay::Present(std::vector<HwcLayer *> &source_layers,

still seeing some warnings
