### ISSUE TITLE
Add support for RGBA16F.

### ISSUE THREAD

**Issue by kalyankondapally** [intel/IA-Hardware-Composer#259]
CTS android.view.cts.PixelCopyTest#testWindowProducerCopyToRGBA16F failing in CtsViewTestCases

**Comment by harishkrupo** [comment]
It fails [here](https://android.googlesource.com/platform/frameworks/base/+/master/libs/hwui/OpenGLReadback.cpp#234) with GL_INVALID_OPERATION error.

**Comment by tpalli** [comment]
You could try to change read type to GL_FLOAT and see if that works out. OpenGL ES 3.2 spec specifies following:

"For floating-point rendering surfaces, the combination format RGBA and type FLOAT is accepted."

I'm not completely sure what the test is expecting here, there are many other invalid format, type combos in that functions that would not be supported.

**Comment by harishkrupo** [comment]
Ok, will try that.

**Comment by md-sami** [comment]
changed to GL_FLOAT , got crash in _mesa_unpack_rgba_row() during glReadPixels call.

**Comment by strassek** [comment]
@kalyankondapally I can take a look at this

**Comment by kalyankondapally** [comment]
@strassek Thanks, can't still assign it to you for some reason.

**Comment by strassek** [comment]
I tried this test against recent (< 1 week old) Android-IA sources and the test case is passing. Could someone who is seeing the issue please identify what revision of Mesa they are testing against?

**Comment by harishkrupo** [comment]
I think this is the TOT where the regression is seen: https://github.com/intel/external-mesa/commit/8731bc35ff 
@sgnanase Could you please verify?

**Comment by harishkrupo** [comment]
Sorry, should have been more specific, please checkout this tree: https://github.com/intel/external-mesa/commit/8731bc35ff.

**Comment by kalyankondapally** [comment]
@harishkrupo Do you have any potential fix for this issue ?

**Comment by kalyankondapally** [comment]
fix merged in our mesa repo
