### ISSUE TITLE
PlaneState is not set correctly when YUV layer is replaced with RGB.

### ISSUE THREAD

**Issue by kalyankondapally** [intel/IA-Hardware-Composer#269]
Steps:
Revert this commit:
https://github.com/intel/IA-Hardware-Composer/commit/95047742df2d368ae601bdff4ce9d4026d685ee4
Play Video from Gallery or any other app.

Expected Result:
Video plays fine till end.

Actual Result:
We see commit failures.

Issue:
At the end of playback we might be getting a buffer with XR24 format.

We can see here that https://github.com/intel/IA-Hardware-Composer/blob/master/common/core/overlaylayer.cpp#L374 is layer format has changed, we ensure to re-render content.

In DisplayPlane state, we track if a plane is scanning out a video layer (i.e. https://github.com/intel/IA-Hardware-Composer/blob/master/common/display/displayplanestate.cpp#L451). We track this to determine if we need to take Media backend for color conversions or 3D Backend. As format has changed now, we would need to inform displayplate state that it's not anymore dealing with YUV format and should take 3D Backend.

One possible solution:
1)Add a state flag in OverlayLayer to indicate when format has changed. i.e. https://github.com/intel/IA-Hardware-Composer/blob/master/common/core/overlaylayer.h#L221
2)Here https://github.com/intel/IA-Hardware-Composer/blob/master/common/display/displayqueue.cpp#L272 check if the flag (from step 1) is set for the layer and if the plane state is actually expecting a packed YUV/planar format( https://github.com/intel/IA-Hardware-Composer/blob/master/common/display/displayplanestate.h#L129). If the flag is set and the plane is expecting Video, check if the format of buffer matches the needs i.e. https://github.com/intel/IA-Hardware-Composer/blob/master/common/core/overlaylayer.h#L172.  If it doesn't,  reset the video plane state in DisplayPlaneState, so it starts using the 3D path.

We might also need to handle the other way, where next frame the layer might be supporting YUV format. We might need to track in DisplayPlaneState if it can support a videolayer (i.e. store this value in another variable before resetting it in Step 2 above)and set it back in case the layer starts using YUV/Planar formats again.

**Comment by stripes416** [comment]
I'll look into this. Thanks for all the info @kalyankondapally
