### ISSUE TITLE
Avoid copying buffer details in DrmBuffer Initialize.

### ISSUE THREAD

**Issue by kalyankondapally** [intel/IA-Hardware-Composer#274]
https://github.com/intel/IA-Hardware-Composer/blob/master/wsi/drm/drmbuffer.cpp#L51  We copy gemhandles, offset, pitches here. We can avoid this as they are part of meta data already. We should clean this up at some point.

**Comment by harishkrupo** [comment]
So, we just store a reference to the passed HwcBuffer and re-use in other places?

**Comment by kalyankondapally** [comment]
ya
