### ISSUE TITLE
coverity: Dead code in Render State.

### ISSUE THREAD

**Issue by kalyankondapally** [intel/IA-Hardware-Composer#277]
Reported Issue:

equality_cond: Jumping to case hwcomposer::kTransform90.
 69      case HWCTransform::kTransform90: {
 70        swap_xy = true;
 71        if (transform & HWCTransform::kReflectX) {
   CID 1465620 (#1 of 2): Logically dead code (DEADCODE) [select issue]
 72          flip_xy[0] = true;
 73          flip_xy[1] = true;
   const: At condition transform & hwcomposer::kReflectY, the value of transform must be equal to 4.
   dead_error_condition: The condition transform & hwcomposer::kReflectY cannot be true.
 74        } else if (transform & HWCTransform::kReflectY) {
   CID 1465620 (#2 of 2): Logically dead code (DEADCODE)dead_error_line: Execution cannot reach this statement: flip_xy[0] = false;.
 75          flip_xy[0] = false;
 76          flip_xy[1] = false;
 77        } else {
 78          flip_xy[0] = false;
 79          flip_xy[1] = true;

**Comment by strassek** [comment]
I'll start on this now

**Comment by strassek** [comment]
The fact that the code in question is dead shows us that there isn't sufficient test coverage. (kTransform90 | kReflectX) and (kTransform90 | kReflectY) ought to be valid transform modes. I will investigate that problem further.
