### ISSUE TITLE
Clone mode, Can we reuse composited FB, instead of do composition again?

### ISSUE THREAD

**Issue by js0701** [intel/IA-Hardware-Composer#295]
If so, PNP will get improved

**Comment by js0701** [comment]
@kalyankondapally

**Comment by kalyankondapally** [comment]
If we are using single plane yes, with multi planes it becomes tricky as the capabilities will change. However, we can defintely leverage things like pane+layer mapping, per plane compositions, do a simple validation if that works on cloned display (i.e. Test commit validation). In this case we can just go with it, if not have fallback path like now. Definitely worth a try.
