### ISSUE TITLE
DisplayManager thread should wake up only for hot plug events.

### ISSUE THREAD

**Issue by kalyankondapally** [intel/IA-Hardware-Composer#296]
This thread is used to monitor for hot plug events, however it wakes up for all drm events. Investigate if we can only wake the thread to handle hot plug events only.

**Comment by csravelar** [comment]
Hey kalyan, what is a good way to reproduce the issue and sanity check that any drm event is being activated?

**Comment by kalyankondapally** [comment]
https://github.com/intel/IA-Hardware-Composer/blob/master/wsi/drm/drmdisplaymanager.cpp#L200  this is where we handle drm events.

This is where we register for event callbacks:
https://github.com/intel/IA-Hardware-Composer/blob/master/wsi/drm/drmdisplaymanager.cpp#L93

**Comment by kalyankondapally** [comment]
Just add logs in Handle Routine and see
