### ISSUE TITLE
Runtime HSBC adjust is not working

### ISSUE THREAD

**Issue by xuguangxin** [intel/IA-Hardware-Composer#332]
this is required by PREQ-28918, we need adjust Hue, Sharepness... when we pause the video
please consider add this

**Comment by strassek** [comment]
Is this a bug or a feature request? Please provide steps for reproduction.

**Comment by xuguangxin** [comment]
From design, we hope we can change hsbc at the pause. Currently, it does not work. You can say it's a bug

step to reproduce:
1. play a  video on Android .
2. pause the video 
3. run 'hwcservice_test -b 100' to adjust Brightness to 100. 
4. you can see no brightness improvement on the screen.
5. unpause the video.
6. now you see the video turn bright

**Comment by xuguangxin** [comment]
@kalyankondapally

**Comment by stripes416** [comment]
@xuguangxin do you remember what video player you were running the video with? Just native or a specific app?

**Comment by js0701** [comment]
https://github.com/intel/IA-Hardware-Composer/commit/21c2f60dfd5044cfa0e640b09d9c42e52a669f00
it may already been fixed by this patch

**Comment by chunge123** [comment]
Can't duplicate this issue on  https://buildbot.sh.intel.com/absp/builders/f_p_opensourcegfx_master-engineering/builds/62 build,
step:
1.play a video on Android .
2.pause the video
3.run 'hwcservice_test -b 100' to adjust Brightness to 100.
4.the video turn bright on the screen.

**Comment by xuguangxin** [comment]
@chunge123 , could you merge OAM-65128 if this landing on GP2.0?

thanks

**Comment by jennycao** [comment]
@xuguangxin @js0701  This patch would be merge to 1A ww37.2.
