### ISSUE TITLE
[Master][Stable][ww23] Can not enter Clone Mode in warm boot (reboot)

### ISSUE THREAD

**Issue by jennycao** [intel/IA-Hardware-Composer#396]
When 2 HDMI displays are connected, one display shows fine, second display does not show the status bar

**Comment by yhe39** [comment]
[error log.txt](https://github.com/intel/IA-Hardware-Composer/files/2113630/error.log.txt)

**Comment by jennycao** [comment]
close this issue since android/o/mr1/master is not used any more
