### ISSUE TITLE
[Master][ww23] Can not enter Mosiac Mode

### ISSUE THREAD

**Issue by jennycao** [intel/IA-Hardware-Composer#397]
System does not go to mosaic display. Seeing a blank screen with no display

**Comment by js0701** [comment]
@jennycao how many commits diffs with stable can you locate which commit cause it

**Comment by yhe39** [comment]
[error log.txt](https://github.com/intel/IA-Hardware-Composer/files/2113627/error.log.txt)

**Comment by jennycao** [comment]
https://github.com/intel/IA-Hardware-Composer/commit/145bf9c5853cb5b0de0136a076d1a8b9b0b1c8dc 
145bf9c5853c Apply damage transformations in GetLayerDamage 
This patch make the mosiac mode failed.
@kalyankondapally @harishkrupo @js0701

**Comment by jennycao** [comment]
close this issue since android/o/mr1/master is not used any more.
