### ISSUE TITLE
Build error with corresponding android10-release minigbm branch

### ISSUE THREAD

**Issue by maurossi** [intel/IA-Hardware-Composer#689]
Hi,
just a question, when trying to build Android Q with android10-release branch of this project,
I am using intel/minigbm project same name branch android10-release,
but I am getting the following building error:

```
external/IA-Hardware-Composer/platformminigbm.cpp:20:10: fatal error: 'i915_private_types.h' file not found
#include "i915_private_types.h"
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

i915_private_types.h is not present in intel/minigbm android10-release branch

How do you build android10-release branch of this project?
And which combination of hwcomposer and gralloc modules are supposed to be used together?
Mauro

**Comment by Shao-Feng** [comment]
Hi,

Could you sync the codes to the latest for Android 10?
this head file "i915_private_types.h" is not used any more.

**Comment by maurossi** [comment]
Hi,
thank for response, I synced this project to android10-release branch and its HEAD commit 3eca0df4b63dd5def28a73d8ec123087f7262f43 introduces an include of i915_private_types.h

Which latest for Android 10 branch are you referring to?

Thanks

**Comment by Shao-Feng** [comment]
add the one into your repo https://github.com/intel/IA-Hardware-Composer.git
and the last commit is https://github.com/intel/IA-Hardware-Composer/commit/f18ffcd7feba1dee61fa8cd9dffd66bde0c2008b

Use the master branch, don't use the branch android10-release, that one is not released one, it is named incorrectly

**Comment by maurossi** [comment]
Thanks a lot
